# src/main/resources/application.yml

server:
  port: 8081

spring:
  application:
    name: ticket
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ticket
  data:
    redis:
      host: localhost
      port: 6379
      password: redis
  devtools:
    livereload:
      enabled: true
  kafka:
    bootstrap-servers: localhost:19092,localhost:29092,localhost:39092

keycloak:
  auth-server-url: http://localhost:8080
  realm: ticket
  resource: ticket-api
  credentials:
    secret: T6SQhxISaFwDU35oDOMMKV1xJaujjXzy
  ssl-required: external

