# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-dp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ticket-db
  template:
    metadata:
      labels:
        app: ticket-db
    spec:
      containers:
        - name: ticket-db
          image: yisakh/ticket-db
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: ticket-db-config
