spring:
  application:
    name: ticket-db
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082