services:
  ticket-api:
    container_name: ticket-api-db
    image: yisakh/ticket-api-db
    env_file:
      - .env.properties
    expose:
      - 8082
    ports:
      - 8082:8082
    tty: true
    environment:
      - TZ=Asia/Seoul
    networks:
      - ticket-api
networks:
  ticket-api:
    external: true