# src/main/resources/application-prd.yml

server:
  port: ${WEB_PORT}

logging:
  level:
    root: ${LOGGING_LEVEL:info}

spring:
  config:
    import: optional:file:.env.properties
  application:
    name: ticket
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/ticket
  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWD}
  devtools:
    livereload:
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_URL}

aspect:
  enabled:${ENABLED}

keycloak:
  auth-server-url: ${KEYCLOAK_URL}
  realm: ${REALM_NAME}
  resource: ${CLIENT_NAME}
  credentials:
    secret: ${CLIENT_SECRET}

ticket:
  max-seat-size: ${MAX_SEAT_SIZE}
  max-retries: ${MAX_RETRIES}
  max-sleep-time: ${MAX_SLEEP_TIME}